// ### CONNECT TO DB ###

// Fine i'll do it myself..
// Couldn't get any npm packages to work with sqlcipher..

import path from 'path';
import 'dotenv/config';
import { execSync } from "child_process";

// import { SELECT } from './select.utils.js'

// Get paths:
const rootPath = path.resolve('./');
const dbPath = rootPath + process.env.DB_PATH;
const dbPass = process.env.DB_PASS;

// EXECUTES a query.
// RETURNS a string.
export function dbQuery(query: string) {
    try {
        // Executes the query, converts it into a string and gets rid of the empty line and the "ok" generated by the pragma key.
        let arr = execSync(`sqlcipher ${dbPath} -cmd "PRAGMA key=${dbPass}" ".headers ON" "${query}"`).toString().split("\n")
        return arr.splice(1, arr.length - 2).join("\n");
    } catch (error: any) {
        return error.message;
    }
}

// ### TEST HERE ###
// console.log(SELECT(['*'], 'User'));
// console.log(SELECT(['*'], 'User', ['user_id > 2', 'user_id < 13']));
// console.log(SELECT(['user_id, user_name'], 'User', undefined, 1))
