#!/bin/bash

echo " CREATE    TABLES    ./db/scripts/create"
echo "   DROP    TABLES    ./db/scripts/drop    (-a / -t TABLE TABLE...)"
echo "  RESET    TABLES    ./db/scripts/reset   (-a / -t TABLE TABLE...)"
echo "   LIST    TABLES    ./db/scripts/list    (\"\" / -sa / -s TABLE TABLE...)"
echo "-----------------------------------------"
echo "ENCRYPT   DATABASE   ./db/scripts/encrypt"
echo -e "\033[1;31mWARNING: Will disable the other scripts from working."
